# MediLink Woodpecker CI Pipeline
# 6-Stage quality gate replacing human code review
# All stages use node:22-alpine to match .nvmrc (Node 22.21.0)
# Stages 4-5 are placeholders until M1-8 (E2E) and M5-5 (VRT) activate them
#
# Environment strategy:
#   - App env vars (CONVEX_*, AUTH_*): loaded from .env.ci via `cp .env.ci .env`
#   - Turbo cache (TURBO_TEAM, TURBO_TOKEN): set via Woodpecker CI secrets
#   - Do NOT declare app vars in environment: section (avoids overriding .env.ci)

when:
  event: [push, pull_request]

steps:
  # Stage 1: Lint + Typecheck + Build (quality gate — must pass before tests run)
  - name: lint-typecheck-build
    image: node:22-alpine
    environment:
      # Turborepo remote caching (set via Woodpecker CI secrets)
      TURBO_TEAM:
        from_secret: turbo_team
      TURBO_TOKEN:
        from_secret: turbo_token
    commands:
      - apk add --no-cache git
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      # Load CI-safe env vars (CONVEX_*, AUTH_*, PORT)
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm typecheck
      - pnpm build

  # Stage 2: Unit Tests (Vitest)
  - name: unit-tests
    image: node:22-alpine
    depends_on: [lint-typecheck-build]
    environment:
      TURBO_TEAM:
        from_secret: turbo_team
      TURBO_TOKEN:
        from_secret: turbo_token
    commands:
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - pnpm test

  # Stage 3: Smoke Test (health endpoint verification)
  - name: smoke-test
    image: node:22-alpine
    depends_on: [unit-tests]
    commands:
      - apk add --no-cache wget
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - echo "Starting Next.js dev server..."
      - pnpm -F @medilink/web dev &
      - echo "Waiting for server to be ready (up to 60 seconds)..."
      - 'for i in $(seq 1 30); do wget -q -O /dev/null http://localhost:3000/api/health && echo "Health check passed" && exit 0; sleep 2; echo "Attempt $i/30..."; done'
      - 'echo "ERROR: Health check failed after 60 seconds" && exit 1'

  # Stage 4: E2E Tests (placeholder — activated by M1-8 #59)
  - name: e2e-tests
    image: node:22-alpine
    depends_on: [smoke-test]
    commands:
      - 'echo "E2E tests: placeholder stage"'
      - 'echo "Will be activated by M1-8 (Playwright E2E setup, issue #59)"'
      - 'echo "Status: SKIP (no tests configured yet)"'

  # Stage 5: Visual Regression Testing (placeholder — activated by M5-5 #80)
  - name: vrt
    image: node:22-alpine
    depends_on: [e2e-tests]
    commands:
      - 'echo "VRT: placeholder stage"'
      - 'echo "Will be activated by M5-5 (VRT baseline setup, issue #80)"'
      - 'echo "Status: SKIP (no baselines configured yet)"'

  # Stage 6: Summary Report
  - name: summary
    image: node:22-alpine
    depends_on:
      - lint-typecheck-build
      - unit-tests
      - smoke-test
      - e2e-tests
      - vrt
    when:
      - status: [success, failure]
    commands:
      - echo "================================"
      - echo "MediLink CI Pipeline Summary"
      - echo "================================"
      - 'echo "Stage 1 (Lint+Typecheck+Build): completed"'
      - 'echo "Stage 2 (Unit Tests): completed"'
      - 'echo "Stage 3 (Smoke Test): completed"'
      - 'echo "Stage 4 (E2E): placeholder (activated by M1-8 #59)"'
      - 'echo "Stage 5 (VRT): placeholder (activated by M5-5 #80)"'
      - echo "================================"
      - echo "Pipeline complete"
