# MediLink Woodpecker CI Pipeline
# 6-Stage quality gate replacing human code review
# All stages use node:22-alpine to match .nvmrc (Node 22.21.0)
# Stage 4 runs smoke.spec.ts only (CI config, no Convex auth); Stage 5 runs VRT (M5-5 #80)
#
# Environment strategy:
#   - App env vars (CONVEX_*, AUTH_*): loaded from .env.ci via `cp .env.ci .env`
#   - Turbo cache (TURBO_TEAM, TURBO_TOKEN): set via Woodpecker CI secrets
#   - CI=true is set per-stage where needed (smoke-test, e2e-tests, vrt)
#   - Do NOT declare app vars in environment: section (avoids overriding .env.ci)
#
# Build uses Turborepo: `pnpm build` at root → `turbo run build` (turbo.json task graph)
# Turborepo remote cache enabled via TURBO_TEAM + TURBO_TOKEN secrets for faster CI

when:
  event: [push, pull_request]

steps:
  # Stage 1: Lint + Typecheck + Build (quality gate — must pass before tests run)
  - name: lint-typecheck-build
    image: node:22-alpine
    environment:
      # Turborepo remote caching (set via Woodpecker CI secrets)
      TURBO_TEAM:
        from_secret: turbo_team
      TURBO_TOKEN:
        from_secret: turbo_token
    commands:
      - apk add --no-cache git
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      # Load CI-safe env vars (CONVEX_*, AUTH_*, PORT)
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - pnpm lint
      - pnpm typecheck
      # turbo run build — Turborepo builds all workspaces in dependency order
      # Equivalent to: pnpm exec turbo run build (root package.json delegates to turbo)
      - pnpm build

  # Stage 2: Unit Tests (Vitest)
  - name: unit-tests
    image: node:22-alpine
    depends_on: [lint-typecheck-build]
    environment:
      TURBO_TEAM:
        from_secret: turbo_team
      TURBO_TOKEN:
        from_secret: turbo_token
    commands:
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - pnpm test

  # Stage 3: Smoke Test (health endpoint verification)
  - name: smoke-test
    image: node:22-alpine
    depends_on: [unit-tests]
    environment:
      # CI=true is required so the /api/health route skips the CI-placeholder CONVEX_URL
      # check (which was added in PR #122). Without CI=true, the health route returns 503
      # for placeholder URLs, causing the wget health check loop to never succeed.
      CI: "true"
    commands:
      - apk add --no-cache wget
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - echo "Starting Next.js dev server..."
      - pnpm -F @medilink/web dev &
      - echo "Waiting for server to be ready (up to 60 seconds)..."
      - 'for i in $(seq 1 30); do wget -q -O /dev/null http://localhost:3000/api/health && echo "Health check passed" && exit 0; sleep 2; echo "Attempt $i/30..."; done'
      - 'echo "ERROR: Health check failed after 60 seconds" && exit 1'

  # Stage 4: E2E Smoke Tests (CI — smoke.spec.ts only, no auth required)
  - name: e2e-tests
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    depends_on: [smoke-test]
    environment:
      NEXTAUTH_URL: "http://localhost:3000"
      # Skip corepack integrity verification (Playwright image has outdated signing keys)
      COREPACK_INTEGRITY_KEYS: "0"
      CI: "true"
    commands:
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - cd apps/web
      - pnpm exec playwright install --with-deps chromium
      - pnpm e2e:ci

  # Stage 5: Visual Regression Testing (VRT)
  - name: vrt
    image: mcr.microsoft.com/playwright:v1.50.0-noble
    depends_on: [e2e-tests]
    failure: ignore
    environment:
      COREPACK_INTEGRITY_KEYS: "0"
      CI: "true"
    commands:
      - corepack enable
      - corepack prepare pnpm@10.19.0 --activate
      - cp .env.ci .env
      - pnpm install --frozen-lockfile
      - cd apps/web
      - pnpm exec playwright install --with-deps chromium
      - pnpm vrt

  # Stage 6: Summary Report
  - name: summary
    image: node:22-alpine
    depends_on:
      - lint-typecheck-build
      - unit-tests
      - smoke-test
      - e2e-tests
      - vrt
    when:
      - status: [success, failure]
    commands:
      - echo "================================"
      - echo "MediLink CI Pipeline Summary"
      - echo "================================"
      - 'echo "Stage 1 (Lint+Typecheck+Build): completed"'
      - 'echo "Stage 2 (Unit Tests): completed"'
      - 'echo "Stage 3 (Smoke Test): completed"'
      - 'echo "Stage 4 (E2E): completed (smoke.spec.ts only, CI config, no auth required)"'
      - 'echo "Stage 5 (VRT): completed (visual regression, landing/sign-in/sign-up, M5-5 #80)"'
      - echo "================================"
      - echo "Pipeline complete"
